apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: floating-ip-a
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: floating-ip-a
  template:
    metadata:
      labels:
        app: floating-ip-a
    spec:
      serviceAccountName: floating-ip
      tolerations:
        - operator: "Exists"
      hostNetwork: true
      containers:
        - name: floating-ip
          image: ghcr.io/sandels-hq/hcloud-floating-ip:latest
          volumeMounts:
            - name: config
              mountPath: /etc/keepalived/keepalived.conf.template
              subPath: keepalived.conf
            - mountPath: /dev
              name: dev
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hcloud
                  key: token
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: floating-ip-a
                  key: DOMAIN
            - name: FLOATING_IP
              valueFrom:
                configMapKeyRef:
                  name: floating-ip-a
                  key: FLOATING_IP
            - name: FLOATING_IP_ID
              valueFrom:
                configMapKeyRef:
                  name: floating-ip-a
                  key: FLOATING_IP_ID
            - name: FLOATING_INTERFACE
              valueFrom:
                configMapKeyRef:
                  name: floating-ip-a
                  key: FLOATING_INTERFACE
            - name: MASTER_NODE
              valueFrom:
                configMapKeyRef:
                  name: floating-ip-a
                  key: MASTER_NODE
            - name: KEEPALIVED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: floating-ip
                  key: keepalived_password
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_BROADCAST
                - NET_RAW
            privileged: true
      volumes:
        - name: config
          configMap:
            name: floating-ip-a
        - name: dev
          hostPath:
            path: /dev
