apiVersion: v1
kind: ConfigMap
metadata:
  name: floating-ip-a
  namespace: kube-system
data:
  DOMAIN: "<DOMAIN USED ON SERVER HOSTNAMES>"
  FLOATING_IP: "<HETZNER FLOATING IP A>"
  FLOATING_IP_ID: "<HETZNER FLOATING IP A ID>"
  FLOATING_INTERFACE: "eth0"
  MASTER_NODE: "<PREFERRED MASTER NODE HOSTNAME>"
  keepalived.conf: |
    global_defs {
        max_auto_priority 99
        enable_script_security
        script_user root
    }
    vrrp_script check_floating_ip {
        script "/check.sh"
        user root
        interval 3
        fall 5
        rise 2
    }
    vrrp_instance vip {
        interface PRIVATE_INTERFACE
        state KEEPALIVED_STATE
        priority KEEPALIVED_PRIORITY
        garp_master_delay 5
        preempt_delay 300
        advert_int 1
        virtual_router_id 11
        unicast_src_ip PRIVATE_IP
        UNICAST_PEERS

        virtual_ipaddress {
            FLOATING_IP dev FLOATING_INTERFACE
        }

        virtual_rules {
            from FLOATING_IP table FLOATING_TABLE priority 1000
        }

        virtual_routes {
            172.31.1.1 dev FLOATING_INTERFACE table FLOATING_TABLE
            default via 172.31.1.1 dev FLOATING_INTERFACE table FLOATING_TABLE
        }

        authentication {
            auth_type PASS
            auth_pass KEEPALIVED_PASSWORD
        }

        track_script {
            check_floating_ip
        }

        notify_master "/master.sh"
        #notify_backup "/backup.sh"
    }
