apiVersion: v1
kind: ConfigMap
metadata:
  name: floating-ip-b
  namespace: kube-system
data:
  DOMAIN: "<DOMAIN USED ON SERVER HOSTNAMES>"
  FLOATING_IP: "<FLOATING IP>"
  FLOATING_IP_ID: "<FLOATING IP ID ON HETZNER>"
  FLOATING_INTERFACE: "eth0:2"
  MASTER_NODE: "<PREFERRED MASTER NODE HOSTNAME>"
  keepalived.conf: |
    vrrp_script check_floating_ip {
        script "/check.sh"
        user root
        interval 3
        fall 5
        rise 2
    }
    vrrp_instance vip {
        interface PRIVATE_INTERFACE
        state KEEPALIVED_STATE
        priority KEEPALIVED_PRIORITY
        garp_master_delay 5

        advert_int 3
        virtual_router_id 12
        unicast_src_ip PRIVATE_IP
        UNICAST_PEERS

        authentication {
            auth_type PASS
            auth_pass KEEPALIVED_PASSWORD
        }

        track_script {
            check_floating_ip
        }

        notify_master "/master.sh"
        notify_backup "/backup.sh"
    }