---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: floating-ip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floating-ip
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: floating-ip
subjects:
- kind: ServiceAccount
  name: floating-ip
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: floating-ip
  apiGroup: rbac.authorization.k8s.io